# Form implementation generated from reading ui file 'dlgExportar.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgexportar(object):
    def setupUi(self, dlgexportar):
        dlgexportar.setObjectName("dlgexportar")
        dlgexportar.resize(308, 151)
        self.buttonBox = QtWidgets.QDialogButtonBox(dlgexportar)
        self.buttonBox.setGeometry(QtCore.QRect(40, 100, 221, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget_4 = QtWidgets.QWidget(dlgexportar)
        self.layoutWidget_4.setGeometry(QtCore.QRect(50, 60, 179, 22))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cbClientes = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cbClientes.setMinimumSize(QtCore.QSize(80, 20))
        self.cbClientes.setMaximumSize(QtCore.QSize(80, 20))
        self.cbClientes.setObjectName("cbClientes")
        self.horizontalLayout_6.addWidget(self.cbClientes)
        self.cbCoches = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cbCoches.setMinimumSize(QtCore.QSize(80, 20))
        self.cbCoches.setMaximumSize(QtCore.QSize(80, 20))
        self.cbCoches.setObjectName("cbCoches")
        self.horizontalLayout_6.addWidget(self.cbCoches)
        self.label = QtWidgets.QLabel(dlgexportar)
        self.label.setGeometry(QtCore.QRect(50, 20, 151, 21))
        self.label.setObjectName("label")

        self.retranslateUi(dlgexportar)
        self.buttonBox.accepted.connect(dlgexportar.accept) # type: ignore
        self.buttonBox.rejected.connect(dlgexportar.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgexportar)

    def retranslateUi(self, dlgexportar):
        _translate = QtCore.QCoreApplication.translate
        dlgexportar.setWindowTitle(_translate("dlgexportar", "Dialog"))
        self.cbClientes.setText(_translate("dlgexportar", "Clientes"))
        self.cbCoches.setText(_translate("dlgexportar", "Coches"))
        self.label.setText(_translate("dlgexportar", "¿Qué datos quiere exportar?"))
