# Form implementation generated from reading ui file 'dlgExportar.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgexportar(object):
    def setupUi(self, dlgexportar):
        dlgexportar.setObjectName("dlgexportar")
        dlgexportar.resize(275, 151)
        dlgexportar.setModal(True)
        self.layoutWidget_4 = QtWidgets.QWidget(dlgexportar)
        self.layoutWidget_4.setGeometry(QtCore.QRect(60, 60, 161, 22))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cbClientes = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cbClientes.setMinimumSize(QtCore.QSize(0, 20))
        self.cbClientes.setMaximumSize(QtCore.QSize(11111, 20))
        self.cbClientes.setObjectName("cbClientes")
        self.horizontalLayout_6.addWidget(self.cbClientes)
        self.cbCoches = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.cbCoches.setMinimumSize(QtCore.QSize(0, 20))
        self.cbCoches.setMaximumSize(QtCore.QSize(11111, 20))
        self.cbCoches.setObjectName("cbCoches")
        self.horizontalLayout_6.addWidget(self.cbCoches)
        self.label = QtWidgets.QLabel(dlgexportar)
        self.label.setGeometry(QtCore.QRect(60, 30, 141, 21))
        self.label.setMinimumSize(QtCore.QSize(141, 21))
        self.label.setMaximumSize(QtCore.QSize(141, 21))
        self.label.setObjectName("label")
        self.btnAceptar = QtWidgets.QPushButton(dlgexportar)
        self.btnAceptar.setGeometry(QtCore.QRect(100, 100, 75, 23))
        self.btnAceptar.setObjectName("btnAceptar")

        self.retranslateUi(dlgexportar)
        QtCore.QMetaObject.connectSlotsByName(dlgexportar)

    def retranslateUi(self, dlgexportar):
        _translate = QtCore.QCoreApplication.translate
        dlgexportar.setWindowTitle(_translate("dlgexportar", "Exportar Datos"))
        self.cbClientes.setText(_translate("dlgexportar", "Clientes"))
        self.cbCoches.setText(_translate("dlgexportar", "Coches"))
        self.label.setText(_translate("dlgexportar", "¿Qué datos quiere exportar?"))
        self.btnAceptar.setText(_translate("dlgexportar", "Aceptar"))
