# Form implementation generated from reading ui file 'dlgSalir.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgSalir(object):
    def setupUi(self, dlgSalir):
        dlgSalir.setObjectName("dlgSalir")
        dlgSalir.resize(300, 200)
        dlgSalir.setMinimumSize(QtCore.QSize(300, 200))
        dlgSalir.setMaximumSize(QtCore.QSize(300, 200))
        dlgSalir.setModal(True)
        self.btnBoxSalir = QtWidgets.QDialogButtonBox(dlgSalir)
        self.btnBoxSalir.setGeometry(QtCore.QRect(-70, 70, 300, 200))
        self.btnBoxSalir.setMinimumSize(QtCore.QSize(300, 200))
        self.btnBoxSalir.setMaximumSize(QtCore.QSize(300, 200))
        self.btnBoxSalir.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnBoxSalir.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnBoxSalir.setObjectName("btnBoxSalir")
        self.lblImagenAviso = QtWidgets.QLabel(dlgSalir)
        self.lblImagenAviso.setGeometry(QtCore.QRect(110, 10, 90, 90))
        self.lblImagenAviso.setMinimumSize(QtCore.QSize(90, 90))
        self.lblImagenAviso.setMaximumSize(QtCore.QSize(90, 90))
        self.lblImagenAviso.setText("")
        self.lblImagenAviso.setPixmap(QtGui.QPixmap("img/aviso_icon.png"))
        self.lblImagenAviso.setScaledContents(True)
        self.lblImagenAviso.setObjectName("lblImagenAviso")
        self.lblMensajeSalir = QtWidgets.QLabel(dlgSalir)
        self.lblMensajeSalir.setGeometry(QtCore.QRect(100, 120, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblMensajeSalir.setFont(font)
        self.lblMensajeSalir.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblMensajeSalir.setObjectName("lblMensajeSalir")

        self.retranslateUi(dlgSalir)
        self.btnBoxSalir.accepted.connect(dlgSalir.accept) # type: ignore
        self.btnBoxSalir.rejected.connect(dlgSalir.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgSalir)

    def retranslateUi(self, dlgSalir):
        _translate = QtCore.QCoreApplication.translate
        dlgSalir.setWindowTitle(_translate("dlgSalir", "Salir"))
        self.lblMensajeSalir.setText(_translate("dlgSalir", "¿Desea salir?"))
